complete -c seetree -s h -l help -d "show this help"
complete -c seetree -l version -d "print version"
complete -c seetree -l once -d "print once and exit"
complete -c seetree -l detach -d "open seetree in a new Ghostty window (macOS only)"
complete -c seetree -l side -d "split the current Ghostty terminal to the right (macOS only)"
complete -c seetree -l install-hook -d "write the FileChanged hook config"
complete -c seetree -l apply -d "apply the hook directly (use with --install-hook)"
complete -c seetree -l theme -d "color scheme" -x -a "claude mono gruvbox nord dracula tokyo-night catppuccin rose-pine solarized"
complete -c seetree -s l -l list -d "list known Claude projects"
